# Generated by Django 2.2.6 on 2019-10-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='needtoknow',
            field=models.CharField(default='', max_length=200, verbose_name='课程须知'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=200, verbose_name='老师告诉你'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='课程讲师'),
        ),
    ]
