# Generated by Django 2.2.6 on 2019-10-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.FloatField(default=0, verbose_name='学习时长(小时)'),
        ),
    ]
