# Generated by Django 2.2.6 on 2019-10-28 17:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20191028_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=ckeditor.fields.RichTextField(verbose_name='课程详细'),
        ),
    ]
