# Generated by Django 2.2.6 on 2019-10-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册密码'), ('forget', '找回密码'), ('change', '修改邮箱')], max_length=28, verbose_name='发送类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='地址'),
        ),
    ]
